#!/usr/bin/env python3
#
# SomeGraphs documentation build configuration file.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# All configuration values have a default; values that are commented out serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory, add these directories to sys.path here.
# If the directory is relative to the documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('..'))

# -- General configuration ---------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be extensions coming with Sphinx (named
# 'sphinx.ext.*') or your custom ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.viewcode',
    'sphinx.ext.todo',
    'sphinxcontrib.jquery',
]

autodoc_member_order = 'bysource'
autosectionlabel_prefix_document = True
nitpicky = True
nitpick_ignore = [
    ('py:class', 'numpy.int8'),
    ('py:class', 'numpy.int16'),
    ('py:class', 'numpy.int32'),
    ('py:class', 'numpy.int64'),
    ('py:class', 'numpy.uint8'),
    ('py:class', 'numpy.uint16'),
    ('py:class', 'numpy.uint32'),
    ('py:class', 'numpy.uint64'),
    ('py:class', 'numpy.float32'),
    ('py:class', 'numpy.float64'),
    ('py:class', 'numpy.ndarray'),
    ('py:class', 'plotly.graph_objs._figure.Figure'),
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'SomeGraphs'
copyright = "2025 Weizmann Institute of Science"
author = "Oren Ben-Kiki"

# The version info for the project you're documenting, acts as replacement for |version| and |release|, also used in
# various other places throughout the built documents.
#
# The short X.Y version.
version = "0.2.0"
# The full version, including alpha/beta/rc tags.
release = version

# The language for content autogenerated by Sphinx.
language = 'en'

# List of patterns, relative to source directory, that match files and directories to ignore when looking for source
# files. This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['v0.2.0', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------

# The theme to use for HTML and HTML Help pages.
# Setting ``html_theme_path`` from ``sphinx_rtd_theme.get_html_theme_path`` is deprecated and warns,
# and the theme is found without it.
html_theme = 'sphinx_rtd_theme'


# -- Options for HTMLHelp output ---------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'somegraphs'


# -- Options for LaTeX output ------------------------------------------

latex_elements = {}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'somegraphs.tex',
     'SomeGraphs Documentation',
     'Oren Ben-Kiki', 'manual'),
]


# -- Options for manual page output ------------------------------------

# One entry per manual page. List of tuples (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'somegraphs',
     'SomeGraphs Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author, dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'somegraphs',
     'SomeGraphs Documentation',
     author,
     'somegraphs',
     'One line description of project.',
     'Miscellaneous'),
]
